# Generated by Django 4.0 on 2023-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'managed': True},
        ),
    ]
