# Generated by Django 4.0 on 2023-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_urls_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='meta',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
